// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sampleGammaCpp2
Rcpp::IntegerVector sampleGammaCpp2(Rcpp::IntegerVector Gammacurr, const arma::mat& totalW, const arma::mat& Xmat, const arma::mat& W, const arma::mat& blockPriorInv, const arma::vec& d, const arma::mat& Y, const arma::mat& ZTilde, Rcpp::CharacterVector responseType, const arma::vec& g, int num_basis, int p, int k, int start, int end, double omegaM, const arma::vec& Rh, const arma::vec& zeta);
RcppExport SEXP _bnpmccr_sampleGammaCpp2(SEXP GammacurrSEXP, SEXP totalWSEXP, SEXP XmatSEXP, SEXP WSEXP, SEXP blockPriorInvSEXP, SEXP dSEXP, SEXP YSEXP, SEXP ZTildeSEXP, SEXP responseTypeSEXP, SEXP gSEXP, SEXP num_basisSEXP, SEXP pSEXP, SEXP kSEXP, SEXP startSEXP, SEXP endSEXP, SEXP omegaMSEXP, SEXP RhSEXP, SEXP zetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type Gammacurr(GammacurrSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type totalW(totalWSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Xmat(XmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type blockPriorInv(blockPriorInvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ZTilde(ZTildeSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type responseType(responseTypeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type g(gSEXP);
    Rcpp::traits::input_parameter< int >::type num_basis(num_basisSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type start(startSEXP);
    Rcpp::traits::input_parameter< int >::type end(endSEXP);
    Rcpp::traits::input_parameter< double >::type omegaM(omegaMSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Rh(RhSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type zeta(zetaSEXP);
    rcpp_result_gen = Rcpp::wrap(sampleGammaCpp2(Gammacurr, totalW, Xmat, W, blockPriorInv, d, Y, ZTilde, responseType, g, num_basis, p, k, start, end, omegaM, Rh, zeta));
    return rcpp_result_gen;
END_RCPP
}
// updateDiffLike
List updateDiffLike(const Rcpp::List& RCurr, const IntegerVector& Z_ind, const arma::mat& ZCurr, const int k, const arma::vec& TUProp, const arma::vec& TLProp, const arma::mat& TU, const arma::mat& TL);
RcppExport SEXP _bnpmccr_updateDiffLike(SEXP RCurrSEXP, SEXP Z_indSEXP, SEXP ZCurrSEXP, SEXP kSEXP, SEXP TUPropSEXP, SEXP TLPropSEXP, SEXP TUSEXP, SEXP TLSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type RCurr(RCurrSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type Z_ind(Z_indSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ZCurr(ZCurrSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type TUProp(TUPropSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type TLProp(TLPropSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type TU(TUSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type TL(TLSEXP);
    rcpp_result_gen = Rcpp::wrap(updateDiffLike(RCurr, Z_ind, ZCurr, k, TUProp, TLProp, TU, TL));
    return rcpp_result_gen;
END_RCPP
}
// compute_Rh
NumericVector compute_Rh(List invRCurr, IntegerVector Z_ind, int k);
RcppExport SEXP _bnpmccr_compute_Rh(SEXP invRCurrSEXP, SEXP Z_indSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type invRCurr(invRCurrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Z_ind(Z_indSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_Rh(invRCurr, Z_ind, k));
    return rcpp_result_gen;
END_RCPP
}
// compute_zeta
NumericVector compute_zeta(NumericMatrix ZCurr, List invRCurr, IntegerVector Z_ind, int k);
RcppExport SEXP _bnpmccr_compute_zeta(SEXP ZCurrSEXP, SEXP invRCurrSEXP, SEXP Z_indSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type ZCurr(ZCurrSEXP);
    Rcpp::traits::input_parameter< List >::type invRCurr(invRCurrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Z_ind(Z_indSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_zeta(ZCurr, invRCurr, Z_ind, k));
    return rcpp_result_gen;
END_RCPP
}
// computeZetaGamma
NumericVector computeZetaGamma(const NumericMatrix& ZCurr, const IntegerVector& Z_ind, const List& invRCurr, int k);
RcppExport SEXP _bnpmccr_computeZetaGamma(SEXP ZCurrSEXP, SEXP Z_indSEXP, SEXP invRCurrSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type ZCurr(ZCurrSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type Z_ind(Z_indSEXP);
    Rcpp::traits::input_parameter< const List& >::type invRCurr(invRCurrSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(computeZetaGamma(ZCurr, Z_ind, invRCurr, k));
    return rcpp_result_gen;
END_RCPP
}
// computeZetaGamma2
NumericVector computeZetaGamma2(const NumericMatrix& ZCurr, const IntegerVector& Z_ind, const List& invRCurr, int k);
RcppExport SEXP _bnpmccr_computeZetaGamma2(SEXP ZCurrSEXP, SEXP Z_indSEXP, SEXP invRCurrSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type ZCurr(ZCurrSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type Z_ind(Z_indSEXP);
    Rcpp::traits::input_parameter< const List& >::type invRCurr(invRCurrSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(computeZetaGamma2(ZCurr, Z_ind, invRCurr, k));
    return rcpp_result_gen;
END_RCPP
}
// computeZetaAndZeta2
List computeZetaAndZeta2(const NumericMatrix& ZCurr, const List& invRCurr, const IntegerVector& Z_ind, int k);
RcppExport SEXP _bnpmccr_computeZetaAndZeta2(SEXP ZCurrSEXP, SEXP invRCurrSEXP, SEXP Z_indSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type ZCurr(ZCurrSEXP);
    Rcpp::traits::input_parameter< const List& >::type invRCurr(invRCurrSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type Z_ind(Z_indSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(computeZetaAndZeta2(ZCurr, invRCurr, Z_ind, k));
    return rcpp_result_gen;
END_RCPP
}
// update_Z_star
NumericMatrix update_Z_star(IntegerVector Z_ind, NumericMatrix WB_x, NumericMatrix Z_star, NumericVector alpha_h, int H);
RcppExport SEXP _bnpmccr_update_Z_star(SEXP Z_indSEXP, SEXP WB_xSEXP, SEXP Z_starSEXP, SEXP alpha_hSEXP, SEXP HSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type Z_ind(Z_indSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type WB_x(WB_xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Z_star(Z_starSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha_h(alpha_hSEXP);
    Rcpp::traits::input_parameter< int >::type H(HSEXP);
    rcpp_result_gen = Rcpp::wrap(update_Z_star(Z_ind, WB_x, Z_star, alpha_h, H));
    return rcpp_result_gen;
END_RCPP
}
// updateZCurr_binom
arma::mat updateZCurr_binom(const Rcpp::List& RCurr, const arma::ivec& Z_ind, arma::mat ZCurr, const int k, const arma::mat& TL, const arma::mat& TU);
RcppExport SEXP _bnpmccr_updateZCurr_binom(SEXP RCurrSEXP, SEXP Z_indSEXP, SEXP ZCurrSEXP, SEXP kSEXP, SEXP TLSEXP, SEXP TUSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type RCurr(RCurrSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type Z_ind(Z_indSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ZCurr(ZCurrSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type TL(TLSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type TU(TUSEXP);
    rcpp_result_gen = Rcpp::wrap(updateZCurr_binom(RCurr, Z_ind, ZCurr, k, TL, TU));
    return rcpp_result_gen;
END_RCPP
}
// updateZCurrGamma2
arma::mat updateZCurrGamma2(const arma::mat& Y, const arma::mat& WB, arma::mat& ZCurr, const arma::vec& gammaAlpha, int countgamma, int k);
RcppExport SEXP _bnpmccr_updateZCurrGamma2(SEXP YSEXP, SEXP WBSEXP, SEXP ZCurrSEXP, SEXP gammaAlphaSEXP, SEXP countgammaSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type WB(WBSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type ZCurr(ZCurrSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gammaAlpha(gammaAlphaSEXP);
    Rcpp::traits::input_parameter< int >::type countgamma(countgammaSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(updateZCurrGamma2(Y, WB, ZCurr, gammaAlpha, countgamma, k));
    return rcpp_result_gen;
END_RCPP
}
// updateCoefficients2
Rcpp::List updateCoefficients2(const int k, const std::string responseType, const arma::vec& d, arma::mat& ZCurr, const arma::mat& WB, const Rcpp::List& invRCurr, const arma::ivec& Z_ind, const arma::vec& Gammacurr, const int start, const int end, const arma::mat& totalW, const arma::mat& Xmat, const int p, const int num_basis, const arma::vec& g, const arma::mat& blockPriorInv, const arma::vec& Rh, const arma::mat& Y, arma::mat var_z, const arma::mat& W, const arma::vec& newGamma, const arma::mat& Wgammastar, int countgamma, const arma::vec& gammaAlpha, int countnegbinom, const arma::vec& negBinomPar, int countbinom, const arma::vec& nTrial, const Rcpp::List& RCurr, const arma::mat& dpropormat, const int s);
RcppExport SEXP _bnpmccr_updateCoefficients2(SEXP kSEXP, SEXP responseTypeSEXP, SEXP dSEXP, SEXP ZCurrSEXP, SEXP WBSEXP, SEXP invRCurrSEXP, SEXP Z_indSEXP, SEXP GammacurrSEXP, SEXP startSEXP, SEXP endSEXP, SEXP totalWSEXP, SEXP XmatSEXP, SEXP pSEXP, SEXP num_basisSEXP, SEXP gSEXP, SEXP blockPriorInvSEXP, SEXP RhSEXP, SEXP YSEXP, SEXP var_zSEXP, SEXP WSEXP, SEXP newGammaSEXP, SEXP WgammastarSEXP, SEXP countgammaSEXP, SEXP gammaAlphaSEXP, SEXP countnegbinomSEXP, SEXP negBinomParSEXP, SEXP countbinomSEXP, SEXP nTrialSEXP, SEXP RCurrSEXP, SEXP dpropormatSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const std::string >::type responseType(responseTypeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type ZCurr(ZCurrSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type WB(WBSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type invRCurr(invRCurrSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type Z_ind(Z_indSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Gammacurr(GammacurrSEXP);
    Rcpp::traits::input_parameter< const int >::type start(startSEXP);
    Rcpp::traits::input_parameter< const int >::type end(endSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type totalW(totalWSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Xmat(XmatSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const int >::type num_basis(num_basisSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type g(gSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type blockPriorInv(blockPriorInvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Rh(RhSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type var_z(var_zSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type newGamma(newGammaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Wgammastar(WgammastarSEXP);
    Rcpp::traits::input_parameter< int >::type countgamma(countgammaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gammaAlpha(gammaAlphaSEXP);
    Rcpp::traits::input_parameter< int >::type countnegbinom(countnegbinomSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type negBinomPar(negBinomParSEXP);
    Rcpp::traits::input_parameter< int >::type countbinom(countbinomSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type nTrial(nTrialSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type RCurr(RCurrSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dpropormat(dpropormatSEXP);
    Rcpp::traits::input_parameter< const int >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(updateCoefficients2(k, responseType, d, ZCurr, WB, invRCurr, Z_ind, Gammacurr, start, end, totalW, Xmat, p, num_basis, g, blockPriorInv, Rh, Y, var_z, W, newGamma, Wgammastar, countgamma, gammaAlpha, countnegbinom, negBinomPar, countbinom, nTrial, RCurr, dpropormat, s));
    return rcpp_result_gen;
END_RCPP
}
// rmvnorm_sample
arma::vec rmvnorm_sample(const arma::vec& mean, const arma::mat& sigma);
RcppExport SEXP _bnpmccr_rmvnorm_sample(SEXP meanSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(rmvnorm_sample(mean, sigma));
    return rcpp_result_gen;
END_RCPP
}
// updateDPParameters
Rcpp::List updateDPParameters(int H, int p2, Rcpp::IntegerVector Z_ind, arma::vec Gammacurr_x, arma::mat W_x, arma::mat Z_star, arma::vec gh, double omegaC, arma::ivec num_pi2, arma::vec alpha_h, arma::vec BCurr_x, arma::mat WB_x);
RcppExport SEXP _bnpmccr_updateDPParameters(SEXP HSEXP, SEXP p2SEXP, SEXP Z_indSEXP, SEXP Gammacurr_xSEXP, SEXP W_xSEXP, SEXP Z_starSEXP, SEXP ghSEXP, SEXP omegaCSEXP, SEXP num_pi2SEXP, SEXP alpha_hSEXP, SEXP BCurr_xSEXP, SEXP WB_xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type H(HSEXP);
    Rcpp::traits::input_parameter< int >::type p2(p2SEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type Z_ind(Z_indSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Gammacurr_x(Gammacurr_xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W_x(W_xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z_star(Z_starSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gh(ghSEXP);
    Rcpp::traits::input_parameter< double >::type omegaC(omegaCSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type num_pi2(num_pi2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type alpha_h(alpha_hSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type BCurr_x(BCurr_xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type WB_x(WB_xSEXP);
    rcpp_result_gen = Rcpp::wrap(updateDPParameters(H, p2, Z_ind, Gammacurr_x, W_x, Z_star, gh, omegaC, num_pi2, alpha_h, BCurr_x, WB_x));
    return rcpp_result_gen;
END_RCPP
}
// updateZCurr
arma::mat updateZCurr(const Rcpp::List& RCurr, const IntegerVector& Z_ind, arma::mat ZCurr, const int k, const arma::mat& TL, const arma::mat& TU);
RcppExport SEXP _bnpmccr_updateZCurr(SEXP RCurrSEXP, SEXP Z_indSEXP, SEXP ZCurrSEXP, SEXP kSEXP, SEXP TLSEXP, SEXP TUSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type RCurr(RCurrSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type Z_ind(Z_indSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ZCurr(ZCurrSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type TL(TLSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type TU(TUSEXP);
    rcpp_result_gen = Rcpp::wrap(updateZCurr(RCurr, Z_ind, ZCurr, k, TL, TU));
    return rcpp_result_gen;
END_RCPP
}
// updateZCurrGamma
NumericVector updateZCurrGamma(NumericMatrix Y, NumericMatrix WB, NumericMatrix& ZCurr, NumericVector gammaAlpha, int countgamma, int k);
RcppExport SEXP _bnpmccr_updateZCurrGamma(SEXP YSEXP, SEXP WBSEXP, SEXP ZCurrSEXP, SEXP gammaAlphaSEXP, SEXP countgammaSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type WB(WBSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type ZCurr(ZCurrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gammaAlpha(gammaAlphaSEXP);
    Rcpp::traits::input_parameter< int >::type countgamma(countgammaSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(updateZCurrGamma(Y, WB, ZCurr, gammaAlpha, countgamma, k));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bnpmccr_sampleGammaCpp2", (DL_FUNC) &_bnpmccr_sampleGammaCpp2, 18},
    {"_bnpmccr_updateDiffLike", (DL_FUNC) &_bnpmccr_updateDiffLike, 8},
    {"_bnpmccr_compute_Rh", (DL_FUNC) &_bnpmccr_compute_Rh, 3},
    {"_bnpmccr_compute_zeta", (DL_FUNC) &_bnpmccr_compute_zeta, 4},
    {"_bnpmccr_computeZetaGamma", (DL_FUNC) &_bnpmccr_computeZetaGamma, 4},
    {"_bnpmccr_computeZetaGamma2", (DL_FUNC) &_bnpmccr_computeZetaGamma2, 4},
    {"_bnpmccr_computeZetaAndZeta2", (DL_FUNC) &_bnpmccr_computeZetaAndZeta2, 4},
    {"_bnpmccr_update_Z_star", (DL_FUNC) &_bnpmccr_update_Z_star, 5},
    {"_bnpmccr_updateZCurr_binom", (DL_FUNC) &_bnpmccr_updateZCurr_binom, 6},
    {"_bnpmccr_updateZCurrGamma2", (DL_FUNC) &_bnpmccr_updateZCurrGamma2, 6},
    {"_bnpmccr_updateCoefficients2", (DL_FUNC) &_bnpmccr_updateCoefficients2, 31},
    {"_bnpmccr_rmvnorm_sample", (DL_FUNC) &_bnpmccr_rmvnorm_sample, 2},
    {"_bnpmccr_updateDPParameters", (DL_FUNC) &_bnpmccr_updateDPParameters, 12},
    {"_bnpmccr_updateZCurr", (DL_FUNC) &_bnpmccr_updateZCurr, 6},
    {"_bnpmccr_updateZCurrGamma", (DL_FUNC) &_bnpmccr_updateZCurrGamma, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_bnpmccr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
