# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sampleGammaCpp2 <- function(Gammacurr, totalW, Xmat, W, blockPriorInv, d, Y, ZTilde, responseType, g, num_basis, p, k, start, end, omegaM, Rh, zeta) {
    .Call(`_bnpmccr_sampleGammaCpp2`, Gammacurr, totalW, Xmat, W, blockPriorInv, d, Y, ZTilde, responseType, g, num_basis, p, k, start, end, omegaM, Rh, zeta)
}

updateDiffLike <- function(RCurr, Z_ind, ZCurr, k, TUProp, TLProp, TU, TL) {
    .Call(`_bnpmccr_updateDiffLike`, RCurr, Z_ind, ZCurr, k, TUProp, TLProp, TU, TL)
}

compute_Rh <- function(invRCurr, Z_ind, k) {
    .Call(`_bnpmccr_compute_Rh`, invRCurr, Z_ind, k)
}

compute_zeta <- function(ZCurr, invRCurr, Z_ind, k) {
    .Call(`_bnpmccr_compute_zeta`, ZCurr, invRCurr, Z_ind, k)
}

computeZetaGamma <- function(ZCurr, Z_ind, invRCurr, k) {
    .Call(`_bnpmccr_computeZetaGamma`, ZCurr, Z_ind, invRCurr, k)
}

computeZetaGamma2 <- function(ZCurr, Z_ind, invRCurr, k) {
    .Call(`_bnpmccr_computeZetaGamma2`, ZCurr, Z_ind, invRCurr, k)
}

computeZetaAndZeta2 <- function(ZCurr, invRCurr, Z_ind, k) {
    .Call(`_bnpmccr_computeZetaAndZeta2`, ZCurr, invRCurr, Z_ind, k)
}

update_Z_star <- function(Z_ind, WB_x, Z_star, alpha_h, H) {
    .Call(`_bnpmccr_update_Z_star`, Z_ind, WB_x, Z_star, alpha_h, H)
}

updateZCurr_binom <- function(RCurr, Z_ind, ZCurr, k, TL, TU) {
    .Call(`_bnpmccr_updateZCurr_binom`, RCurr, Z_ind, ZCurr, k, TL, TU)
}

updateZCurrGamma2 <- function(Y, WB, ZCurr, gammaAlpha, countgamma, k) {
    .Call(`_bnpmccr_updateZCurrGamma2`, Y, WB, ZCurr, gammaAlpha, countgamma, k)
}

updateCoefficients2 <- function(k, responseType, d, ZCurr, WB, invRCurr, Z_ind, Gammacurr, start, end, totalW, Xmat, p, num_basis, g, blockPriorInv, Rh, Y, var_z, W, newGamma, Wgammastar, countgamma, gammaAlpha, countnegbinom, negBinomPar, countbinom, nTrial, RCurr, dpropormat, s) {
    .Call(`_bnpmccr_updateCoefficients2`, k, responseType, d, ZCurr, WB, invRCurr, Z_ind, Gammacurr, start, end, totalW, Xmat, p, num_basis, g, blockPriorInv, Rh, Y, var_z, W, newGamma, Wgammastar, countgamma, gammaAlpha, countnegbinom, negBinomPar, countbinom, nTrial, RCurr, dpropormat, s)
}

rmvnorm_sample <- function(mean, sigma) {
    .Call(`_bnpmccr_rmvnorm_sample`, mean, sigma)
}

updateDPParameters <- function(H, p2, Z_ind, Gammacurr_x, W_x, Z_star, gh, omegaC, num_pi2, alpha_h, BCurr_x, WB_x) {
    .Call(`_bnpmccr_updateDPParameters`, H, p2, Z_ind, Gammacurr_x, W_x, Z_star, gh, omegaC, num_pi2, alpha_h, BCurr_x, WB_x)
}

updateZCurr <- function(RCurr, Z_ind, ZCurr, k, TL, TU) {
    .Call(`_bnpmccr_updateZCurr`, RCurr, Z_ind, ZCurr, k, TL, TU)
}

updateZCurrGamma <- function(Y, WB, ZCurr, gammaAlpha, countgamma, k) {
    .Call(`_bnpmccr_updateZCurrGamma`, Y, WB, ZCurr, gammaAlpha, countgamma, k)
}

